### ISSUE TITLE
能修改默认翻译引擎嘛？

### ISSUE THREAD

**Issue by FeulerLoup** [zyufstudio/TM#3]
默认的有道引擎经常翻译不出来，每次都要手动选谷歌。
可以麻烦声明个变量啥的让我们自己指定嘛？

**Comment by zyufstudio** [comment]
有设置的。点击油猴图标就可以看到设置了。在设置中设置需要的默认翻译引擎。

**Comment by zyufstudio** [comment]
有设置的。点击油猴图标就可以看到设置了。在设置中设置需要的默认翻译引擎。

**Comment by FeulerLoup** [comment]
哦哦，看到了，谢谢
